Bugfix and some QoL
rug-cit-hpc/cluster-utilities pull request #10
Opened 2021-07-24 13:09 UTC by klemenvon

Some changes to how we handle terminal colors internally. Fixed bug where student numbers would get cut off too far when prettifying user IDs. These changes are only tested for staff account with no quota overruns. Should be fully tested before deploying new version. Do that before accepting the PR.

2021-07-26 07:27 UTC, bedroge requested changes
I've made some style changes, and requested some more changes.
We should also remove all the commented lines (old functionality, e.g. the `colors` dict).

2021-07-26 07:27 UTC, bedroge commented on pgquota/pgquota
>  #!/usr/bin/env python3
```suggestion
#!/usr/bin/python3
```
Let's stick to the OS Python here, as discussed on Slack.

2021-07-26 07:27 UTC, bedroge commented on pgquota/pgquota
> +            print("{}Debug Raw{}".format(colors.get('red'), colors.get('end')))
`colors` has to be replaced here.

2021-07-26 07:27 UTC, bedroge commented on pgquota/pgquota
> +            print("{}End of Debug Raw{}".format(colors.get('red'), colors.get('end')))
and here

2021-07-26 07:27 UTC, bedroge commented on pgquota/pgquota
> +            print("{}Debug object variables{}".format(colors.get('red'), colors.get('end')))
and here

2021-07-26 07:27 UTC, bedroge commented on pgquota/pgquota
> +            print("{}End Debug ojbect variables{}".format(colors.get('red'), colors.get('end')))
and here too.

2021-07-26 07:27 UTC, bedroge commented on pgquota/pgquota
> +class Col():
I'd just name it Color?

2021-09-20 16:14 UTC, klemenvon commented
Addressed all the issues and entirely removed old (commented out) code or reduce fluff. Updated the RPM spec file as well, so all this needs is one more good look and then we can install it.

2021-09-21 11:49 UTC, klemenvon reviewed
Made requested changes and deleted old, commented out code.

2021-09-21 11:52 UTC, bedroge approved these changes

2021-09-21 11:53 UTC, merged